version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo "npm install"
            - npm install 
    build:
        commands:
            - echo "npm build"
            - npm run-script build